### MySQL Database Configuration ###
spring:
  application:
    name: batch-processing-with-spring-batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch_db?useUnicode=true&characterEncoding=utf8&useSSL=false
    name: MySQL Connection
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show_sql: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # disable this property to prevent to autostart of spring jobs