# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# Feign Configuration
feign:
  cat:
    fact:
      name: cat-fact-ninja
      url: https://catfact.ninja
